### ISSUE TITLE
Question for experiments on OOD splits

### ISSUE THREAD

**Issue by minjoong507** [IMCCretrieval/MomentDiff#2]
Hi, I have checked the script files for training Charades-CD and ActivityNet-CD. 
Based on your script files, it appears that the model uses the test-ood split instead of the val split for evaluation during training. 
I would like to confirm if you have correctly evaluated the model on test-ood splits and reported the results in Table 4.

I am trying to reproduce the model. However, I have noticed that the query features are not provided yet.

**Comment by IMCCretrieval** [comment]
Thank you for your attention. Because we just want to quickly observe the results of the model compared to the baseline.
Therefore, similar to MMN's Charades data set settings https://github.com/MCG-NJU/MMN/blob/main/configs/pool_charades_16x16_k5l8.yaml, we reproduced the baseline methods and directly evaluated four methods (MMN,2DTAN, MomentDETR and Ours) on the test set.
In the future, we will follow your suggestion for test set evaluation when comparing with SOTA methods.

There are many ways to obtain text features. For example:
1. Glove features can be extracted through NLTKTokenizer.
2. You can also refer to https://github.com/minghangz/cpl/tree/main/data
